### ISSUE TITLE
Xgboost

### ISSUE THREAD

**Issue by MustaqAhamed** [i5han2/Crime_analysis_and_prediction#1]
How did you install **Xgboost** for this project?
Have you done using **pip install xgboost** or using the wheel **file** given in your project folder?
Also, there is some internal server problem in running the crime and city model for predicting when clicked on the predict button?
Could you help in resolving it??

**Comment by i5han2** [comment]
Actually I used the wheel file. And regarding the internal server error problem, I think it's a problem related to heroku where I have hosted the site. I'll try to resolve it

**Comment by MustaqAhamed** [comment]
Even when am running in localhost it shows an internal server error.
I will be waiting for your update buddy!!Even am trying to resolve it too!!

**Comment by i5han2** [comment]
Oh is it? Actually I haven't visited this project for a long time. Need to check. I'll let you know as soon as I have an update. Can you please elaborate on the error you are getting

**Comment by MustaqAhamed** [comment]
![Internal server error](https://user-images.githubusercontent.com/44725818/167702378-92a7e2de-ff4d-4b91-90b4-3a2a9d1d82cf.PNG)
This is the error that is shown after clicking on predict in Predict By time module.
![predict_crime](https://user-images.githubusercontent.com/44725818/167702718-d2dee0ed-a6ac-4ee7-b6ba-8ed228175d73.PNG)

**Comment by MustaqAhamed** [comment]
Hey buddy, just to update you!!
I installed GDAL and Fiona and got rid of the internal server problem. Your project is working fine now.
By the way, your project is really great and you have made good use of the flask framework by this concept.

You can close this issue now buddy!!

Thanks!!

**Comment by i5han2** [comment]
Thanks a lot! Please feel free to add any feature. I'll be more than happy to merge the PR
